### ISSUE TITLE
Unable to get the installation going correctly

### ISSUE THREAD

**Issue by shankarvn** [qri-io/starpg#6]
When I run make after cloning the repo, I get this error

⚠  2 problems (0 errors, 2 warnings)
✨  Done in 42.03s.

installing go deps

go get -v -u go.starlark.net/starlark github.com/sirupsen/logrus github.com/qri-io/starlib
get "mvdan.cc/unparam": found meta tag get.metaImport{Prefix:"mvdan.cc/unparam", VCS:"git", RepoRoot:"https://github.com/mvdan/unparam"} at //mvdan.cc/unparam?go-get=1
go: github.com/qri-io/starlib@v0.4.0 requires
	github.com/qri-io/dataset@v0.1.1 requires
	github.com/qri-io/qfs@v0.1.0 requires
	github.com/ipfs/go-ipfs@v0.4.21 requires
	github.com/go-critic/go-critic@v0.0.0-20181204210945-ee9bf5809ead: invalid pseudo-version: does not match version-control timestamp (2019-02-10T22:04:43Z)
make: *** [install-deps] Error 1

Not sure what this means.

Thanks

**Comment by FareesHussain** [comment]
@b5 I get this error is this same here

`go get github.com/qri-io/starpg`

```
# github.com/qri-io/starlib/xlsx
../go/src/github.com/qri-io/starlib/xlsx/xlsx.go:96:25: multiple-value f.xlsx.GetRows() in single-value context

```

**Comment by dustmop** [comment]
Apologies @shankarvn that this took so long, but I opened a pull request to fix your issue: https://github.com/qri-io/starpg/pull/12. Looks like the dependencies in `go.mod` are just old. If you try my branch `bump-deps` it should build ok.

Hi @FareesHussain did you try instead cloning the repo and then running `make`? Also, what version of `go` are you using?

**Comment by FareesHussain** [comment]
@dustmop yes, I cloned the repo.

![image](https://user-images.githubusercontent.com/54740946/112571591-64659f80-8e0e-11eb-9b39-72795d70d121.png)

**Comment by dustmop** [comment]
@FareesHussain ah, I think you need to upgrade your `go` version. I think at least 1.13 is required. I'm using 1.14, personally. Might be worth trying to upgrade `yarn`, as well. I'm using yarn 1.21.1 on my machine.

**Comment by FareesHussain** [comment]
@dustmop Thanks, it is working now.
I did install go and yarn recently but it looks like I've followed the wrong installation steps

**Comment by FareesHussain** [comment]
@dustmop I get this error when i run make

```
performance
  0:0  warning  The following asset(s) exceed the recommended size limit (244 KiB).
                Assets: 
                  css.worker.js (616 KiB)
                  typescript.worker.js (3.7 MiB)
                  app.js (2.06 MiB)
  0:0  warning  The following entrypoint(s) combined asset size exceeds the recommended
                limit (244 KiB). This can impact web performance.
                Entrypoints:
                  main (2.06 MiB)
                    app.js

⚠  2 problems (0 errors, 2 warnings)
Done in 368.89s.

installing go deps

go get -v -u go.starlark.net/starlark github.com/sirupsen/logrus github.com/qri-io/starlib
get "mvdan.cc/unparam": found meta tag vcs.metaImport{Prefix:"mvdan.cc/unparam", VCS:"git", RepoRoot:"https://github.com/mvdan/unparam"} at //mvdan.cc/unparam?go-get=1
go: github.com/qri-io/starlib@v0.4.0 requires
	github.com/qri-io/dataset@v0.1.1 requires
	github.com/qri-io/qfs@v0.1.0 requires
	github.com/ipfs/go-ipfs@v0.4.21 requires
	github.com/go-critic/go-critic@v0.0.0-20181204210945-ee9bf5809ead: invalid pseudo-version: does not match version-control timestamp (expected 20190210220443)
makefile:16: recipe for target 'install-deps' failed
make: *** [install-deps] Error 1

```

**Comment by dustmop** [comment]
@FareesHussain this error matches the one originally reported in this issue. See my earlier explanation here: https://github.com/qri-io/starpg/issues/6#issuecomment-807899115. You can change to the git branch `bump-deps` to pick up the fix.

**Comment by FareesHussain** [comment]
@dustmop I get this error at the end of `make`
```
start service

go install && starpg
/bin/sh: 1: starpg: not found
makefile:20: recipe for target 'start' failed
make: *** [start] Error 127

```

**Comment by dustmop** [comment]
@FareesHussain this is a PATH environment variable problem, see https://stackoverflow.com/a/36083961.

**Comment by FareesHussain** [comment]
@dustmop Thanks, It ran successfully :tada:

**Comment by dustmop** [comment]
Glad to help!

Original issue has had its fix merged, closing this now.
